### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by AmingWu** [anton-bushuiev/PPIformer#4]
Dear Authors,

Do you release all the code and dataset for training and evaluation?

Thanks

**Comment by anton-bushuiev** [comment]
Dear @AmingWu ,

Yes, the code and the dataset are already available and the documentation will be added in June.

Specifically, the [`run.py`](https://github.com/anton-bushuiev/PPIformer/blob/main/scripts/run.py) script can be used for both training and evaluation using appropriate Hydra configs from the `configs` directory. The [PPIRef repository](https://github.com/anton-bushuiev/PPIRef) contains the pre-training dataset and the SKEMPI v2.0 dataset used for fine-tuning and testing is available [here](https://github.com/anton-bushuiev/mutils/tree/main/mutils/datasets/SKEMPI2).

Please let me know if you have any question before the documentation is available. I am aiming to add it as soon as possible, which was also blocked by the maintenance break of the infrastructure we used for the development.

**Comment by anton-bushuiev** [comment]
Hi @AmingWu ! I have added examples of training and testing. Please let me know if you encounter any issues. I apologise for the delay.
