### ISSUE TITLE
Possibly an interesting structure to test

### ISSUE THREAD

**Issue by amin-sagar** [anton-bushuiev/PPIformer#5]
Hello.
This is similar to #1 

I used both PPIformer and RDE-PPI for predicting the effect of an Alanine scan on the chains B and C of PDB ID: 8TCG
The residue D12 in chain C is involved in multiple hydrogens with chain B and is known to be absolutely essential for binding as it forms the conserved RGD motif.

![image](https://github.com/anton-bushuiev/PPIformer/assets/118898409/b3933a3d-7919-4ae4-8973-485c8bfbe0b2)

RDE-PPI predicts that mutating this D to A will actually stabilize the interaction.[https://github.com/luost26/RDE-PPI/issues/6](url)

PPIformer does predict it to be destabilizing but the ddg is very small (0.3). Here is the complete scan.
![image](https://github.com/anton-bushuiev/PPIformer/assets/118898409/bd96c8ac-bbec-404e-a1f8-52e1179021ed)

And the zoom to the more important region.
![image](https://github.com/anton-bushuiev/PPIformer/assets/118898409/ee7579b4-80b8-40b5-9a5d-e77b55fa5700)

Many other mutations are predicted to be much more destabilizing than D12A. 
May be this is just because all the mutations can't be predicted correctly and this is within the margin of error. But, if you have some suggestions, I would be very grateful.

Otherwise, I am just putting it here to hopefully contribute to improving the algorithm.

Best,
Amin.

**Comment by anton-bushuiev** [comment]
Hi Amin!

Thank you very much for this analysis! This is extremely valuable. It will be a great case study to test with a new version of the model. I will let you know if I have any interesting update on this.

Best,
Anton
